/**
 * Labour Rate Library - SMM7 2023
 * Real labour rates from SMM7 2023 database
 */

export interface LabourRate {
  id: string;
  code: string;
  trade: string;
  description: string;
  hourlyRate: number; // £ per hour
  dailyRate: number; // £ per day (8 hours)
  productivityFactor: number; // 0-1, default 1.0
  overtimeRate: number; // multiplier (e.g., 1.5 for time-and-a-half)
  costCode: string;
}

export const LABOUR_RATES: LabourRate[] = [
  {
    id: 'labour-001',
    code: 'LK0001UKS',
    trade: 'Lift Installation Gang',
    description: 'Lift Installation Gang (3+1)',
    hourlyRate: 119.11,
    dailyRate: 952.88,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-002',
    code: 'LE1002UKS',
    trade: 'Metalwork Gang',
    description: 'Metalwork Gang (3+1)',
    hourlyRate: 91.09,
    dailyRate: 728.72,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-003',
    code: 'LH5001UKS',
    trade: 'Patent Glazing Gang',
    description: 'Patent Glazing Gang (3+1)',
    hourlyRate: 91.09,
    dailyRate: 728.72,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-004',
    code: 'LH5002UKS',
    trade: 'Curtain Walling Gang',
    description: 'Curtain Walling Gang (3+1)',
    hourlyRate: 91.09,
    dailyRate: 728.72,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-005',
    code: 'LH5003UKS',
    trade: 'Brise Soleil Fixing Gang',
    description: 'Brise Soleil Fixing Gang (3+1)',
    hourlyRate: 91.09,
    dailyRate: 728.72,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-006',
    code: 'LH5004UKS',
    trade: 'Rainscreen Cladding Gang',
    description: 'Rainscreen Cladding Gang (3+1)',
    hourlyRate: 91.09,
    dailyRate: 728.72,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-007',
    code: 'LE0016UKS',
    trade: 'Piling Gang',
    description: 'Piling Gang (1+3)',
    hourlyRate: 78.95,
    dailyRate: 631.60,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-008',
    code: 'LD0302UKS',
    trade: 'Bricklaying Gang',
    description: 'Bricklaying Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-009',
    code: 'LD0305UKS',
    trade: 'Cavity Insulation Gang',
    description: 'Cavity Insulation Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-010',
    code: 'LG5003UKS',
    trade: 'Felt Roofing Gang',
    description: 'Felt Roofing Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-011',
    code: 'LG5005UKS',
    trade: 'Mastic Asphalt Gang',
    description: 'Mastic Asphalt Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-012',
    code: 'LG5020UKS',
    trade: 'Roof Cladding Gang',
    description: 'Roof Cladding Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-013',
    code: 'LG5201UKS',
    trade: 'Flat Roofing Gang',
    description: 'Flat Roofing Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-014',
    code: 'LJ2001UKS',
    trade: 'Plastering Gang',
    description: 'Plastering Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-015',
    code: 'LJ2003UKS',
    trade: 'Tacking Gang',
    description: 'Tacking Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-016',
    code: 'LJ2005UKS',
    trade: 'Partition Gang',
    description: 'Partition Gang (2+1)',
    hourlyRate: 66.80,
    dailyRate: 534.40,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-017',
    code: 'LB5011UKS',
    trade: 'Earthwork Support Gang',
    description: 'Earthwork Support Gang (1+2)',
    hourlyRate: 60.73,
    dailyRate: 485.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-018',
    code: 'LB5014UKS',
    trade: 'Drainlaying Cast Iron Gang',
    description: 'Drainlaying Cast Iron Gang (1+2)',
    hourlyRate: 60.73,
    dailyRate: 485.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-019',
    code: 'LE0030UKS',
    trade: 'Tarmacadam Gang',
    description: 'Tarmacadam Gang (1+2)',
    hourlyRate: 60.73,
    dailyRate: 485.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-020',
    code: 'LE0031UKS',
    trade: 'Surface Dressing Gang',
    description: 'Surface Dressing Gang (1+2)',
    hourlyRate: 60.73,
    dailyRate: 485.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-021',
    code: 'LQ5101UKS',
    trade: 'Plumbing Gang',
    description: 'Plumbing Gang (1+1)',
    hourlyRate: 54.66,
    dailyRate: 437.28,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-022',
    code: 'LB5007UKS',
    trade: 'Masonry Gang',
    description: 'Masonry Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-023',
    code: 'LB5008UKS',
    trade: 'Roofing Gang',
    description: 'Roofing Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-024',
    code: 'LB5009UKS',
    trade: 'Plastering Gang',
    description: 'Plastering Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-025',
    code: 'LB5018UKS',
    trade: 'Fencing Gang',
    description: 'Fencing Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-026',
    code: 'LE1005UKS',
    trade: 'Steelwork Gang',
    description: 'Steelwork Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-027',
    code: 'LF2003UKS',
    trade: 'Carpentry Gang',
    description: 'Carpentry Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-028',
    code: 'LJ1010UKS',
    trade: 'Spray Paint Gang',
    description: 'Spray Paint Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-029',
    code: 'LJ2002UKS',
    trade: 'Suspended Ceiling Gang',
    description: 'Suspended Ceiling Gang (1+1)',
    hourlyRate: 42.51,
    dailyRate: 340.08,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-030',
    code: 'LC1003UKS',
    trade: 'Reinforced Concrete Gang',
    description: 'Reinforced Concrete Gang (1+2)',
    hourlyRate: 36.44,
    dailyRate: 291.52,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL02',
  },
  {
    id: 'labour-031',
    code: 'LR9012UKS',
    trade: 'Lift Engineer',
    description: 'Lift Engineer',
    hourlyRate: 33.63,
    dailyRate: 269.04,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-032',
    code: 'LB5004UKSA',
    trade: 'Plumber',
    description: 'Plumber',
    hourlyRate: 32.18,
    dailyRate: 257.44,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-033',
    code: 'LB5005UKS',
    trade: 'Electrician',
    description: 'Electrician',
    hourlyRate: 30.98,
    dailyRate: 247.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-034',
    code: 'LA1000HAN',
    trade: 'Groundworks Craftsman',
    description: 'Groundworks Craftsman',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-035',
    code: 'LB5003UKS',
    trade: 'General Craftsman',
    description: 'General Craftsman',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-036',
    code: 'LB5015UKS',
    trade: 'DPC Installer',
    description: 'DPC Installer',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-037',
    code: 'LC1002UKS',
    trade: 'Shuttering Carpenter',
    description: 'Shuttering Carpenter',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-038',
    code: 'LC1004UKS',
    trade: 'Steel Fixer',
    description: 'Steel Fixer',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-039',
    code: 'LD0301UKS',
    trade: 'Bricklayer',
    description: 'Bricklayer',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-040',
    code: 'LE1001UKS',
    trade: 'Metalworker Craftsman',
    description: 'Metalworker Craftsman',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-041',
    code: 'LF2001UKS',
    trade: 'Carpenter',
    description: 'Carpenter',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-042',
    code: 'LF2004UKS',
    trade: 'Joiner',
    description: 'Joiner',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-043',
    code: 'LG5001UKS',
    trade: 'Roof Tiler',
    description: 'Roof Tiler',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-044',
    code: 'LG5004UKS',
    trade: 'Sheet Metal Roofer',
    description: 'Sheet Metal Roofer',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-045',
    code: 'LH5000UKS',
    trade: 'Glazier',
    description: 'Glazier',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-046',
    code: 'LJ1001UKS',
    trade: 'Plasterer',
    description: 'Plasterer',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-047',
    code: 'LJ1005UKS',
    trade: 'Painter',
    description: 'Painter',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-048',
    code: 'LJ1008UKS',
    trade: 'Floor / Wall Tiler',
    description: 'Floor / Wall Tiler',
    hourlyRate: 24.29,
    dailyRate: 194.32,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-049',
    code: 'LB5004UKS',
    trade: 'Plumber\'s Labourer',
    description: 'Plumber\'s Labourer',
    hourlyRate: 22.48,
    dailyRate: 179.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
  {
    id: 'labour-050',
    code: 'LB5006UKS',
    trade: 'Electrician\'s Labourer',
    description: 'Electrician\'s Labourer',
    hourlyRate: 22.48,
    dailyRate: 179.84,
    productivityFactor: 0.95,
    overtimeRate: 1.5,
    costCode: 'NL01',
  },
];

export const getLabourByTrade = (trade: string): LabourRate | undefined => {
  return LABOUR_RATES.find((r) => r.trade.toLowerCase().includes(trade.toLowerCase()));
};

export const getLabourByCode = (code: string): LabourRate | undefined => {
  return LABOUR_RATES.find((r) => r.code === code);
};
