/**
 * Plant & Equipment Rate Library - SMM7 2023
 * Real plant hire rates from SMM7 2023 database
 */

export interface PlantRate {
  id: string;
  code: string;
  name: string;
  category: string;
  description: string;
  rate: number; // £ per unit
  unit: string; // hr, day, week, etc.
  costCode: string;
}

export const PLANT_RATES: PlantRate[] = [
  {
    id: 'plant-001',
    code: 'PD0190UKS',
    name: 'Auger Rig Type SB350AD',
    category: 'general',
    description: 'Auger Rig Type SB350AD',
    rate: 224.45,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-002',
    code: 'PD0191UKS',
    name: 'Pile Driving Rig including operator',
    category: 'general',
    description: 'Pile Driving Rig including operator',
    rate: 206.76,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-003',
    code: 'PB0010UKS',
    name: 'Skip including rental & tip fees including lower l',
    category: 'general',
    description: 'Skip including rental & tip fees including lower landfill tax rate',
    rate: 44.83,
    unit: 'm3',
    costCode: 'NP03',
  },
  {
    id: 'plant-004',
    code: 'PE1012UKS',
    name: '10 Tonne Mobile Crane including operator',
    category: 'lifting',
    description: '10 Tonne Mobile Crane including operator',
    rate: 44.71,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-005',
    code: 'PC2020UKS',
    name: 'Galvanising Tank Complete',
    category: 'general',
    description: 'Galvanising Tank Complete',
    rate: 43.17,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-006',
    code: 'PE0134UKS',
    name: 'Hymac 580 Excavator including operator',
    category: 'earthmoving',
    description: 'Hymac 580 Excavator including operator',
    rate: 42.41,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-007',
    code: 'PB4009UKS',
    name: 'Excavator, 360 degrees, blade, back hoe, 6t, 1.5t ',
    category: 'earthmoving',
    description: 'Excavator, 360 degrees, blade, back hoe, 6t, 1.5t breaker including operator',
    rate: 41.67,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-008',
    code: 'PB4025UKS',
    name: 'Mechanical Paver',
    category: 'general',
    description: 'Mechanical Paver',
    rate: 35.96,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-009',
    code: 'PB4001UKS',
    name: 'JCB 3CX including operator',
    category: 'general',
    description: 'JCB 3CX including operator',
    rate: 35.34,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-010',
    code: 'PB4013UKS',
    name: 'Vibrating Roller 6 - 8 Tonne including operator',
    category: 'compaction',
    description: 'Vibrating Roller 6 - 8 Tonne including operator',
    rate: 32.69,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-011',
    code: 'PB4015UKS',
    name: 'Dumper 4WD hydraulic tip 2t including operator',
    category: 'general',
    description: 'Dumper 4WD hydraulic tip 2t including operator',
    rate: 28.85,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-012',
    code: 'PB0009UKS',
    name: 'Muck away lorry & tip fees including lower landfil',
    category: 'general',
    description: 'Muck away lorry & tip fees including lower landfill tax rate',
    rate: 25.40,
    unit: 'm3',
    costCode: 'NP03',
  },
  {
    id: 'plant-013',
    code: 'PG4001UKS',
    name: 'Bitumen Melting Machine + Gas',
    category: 'general',
    description: 'Bitumen Melting Machine + Gas',
    rate: 15.88,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-014',
    code: 'PC2005UKS',
    name: 'Compressor & Two Hoses',
    category: 'general',
    description: 'Compressor & Two Hoses',
    rate: 11.77,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-015',
    code: 'PB4004UKS',
    name: '260 CFM compressor - 4 tool',
    category: 'general',
    description: '260 CFM compressor - 4 tool',
    rate: 9.67,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-016',
    code: 'PD0195UKS',
    name: 'Load Measuring Equipment Package',
    category: 'general',
    description: 'Load Measuring Equipment Package',
    rate: 9.25,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-017',
    code: 'PF0112UKS',
    name: 'Beam Vibrator: 5.2m Unit',
    category: 'general',
    description: 'Beam Vibrator: 5.2m Unit',
    rate: 6.41,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-018',
    code: 'PM1002UKS',
    name: 'Paint Sprayer',
    category: 'general',
    description: 'Paint Sprayer',
    rate: 5.56,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-019',
    code: 'PD0160UKS',
    name: 'Heavy Duty Power Washer',
    category: 'power',
    description: 'Heavy Duty Power Washer',
    rate: 4.85,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-020',
    code: 'PD0150UKS',
    name: 'Chain Saw: Petrol',
    category: 'general',
    description: 'Chain Saw: Petrol',
    rate: 4.02,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-021',
    code: 'PB4020UKS',
    name: 'Post Hole Borer; Two Man',
    category: 'general',
    description: 'Post Hole Borer; Two Man',
    rate: 3.92,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-022',
    code: 'PB4021UKS',
    name: 'Post Rammer',
    category: 'general',
    description: 'Post Rammer',
    rate: 3.23,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-023',
    code: 'PB4005UKS',
    name: 'Pneumatic Breaker & Hose',
    category: 'general',
    description: 'Pneumatic Breaker & Hose',
    rate: 3.04,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-024',
    code: 'PC2002UKS',
    name: 'Handheld powerfloat',
    category: 'power',
    description: 'Handheld powerfloat',
    rate: 2.79,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-025',
    code: 'PB4007UKS',
    name: 'Acrow Prop & Needle Set',
    category: 'general',
    description: 'Acrow Prop & Needle Set',
    rate: 2.70,
    unit: 'day',
    costCode: 'NP02',
  },
  {
    id: 'plant-026',
    code: 'PJ3001UKS',
    name: 'Cartridge Gun',
    category: 'general',
    description: 'Cartridge Gun',
    rate: 2.53,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-027',
    code: 'PC2007UKS',
    name: 'Scabbler',
    category: 'general',
    description: 'Scabbler',
    rate: 2.44,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-028',
    code: 'PB4002UKS',
    name: 'Wacker plate; reversible compactor - Bomag BPR 55/',
    category: 'compaction',
    description: 'Wacker plate; reversible compactor - Bomag BPR 55/65D',
    rate: 2.28,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-029',
    code: 'PE1013UKS',
    name: '2.5 Tonne Block & Tackle',
    category: 'general',
    description: '2.5 Tonne Block & Tackle',
    rate: 2.15,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-030',
    code: 'PB4017UKS',
    name: 'Turf Cutter 300mm wide cut',
    category: 'general',
    description: 'Turf Cutter 300mm wide cut',
    rate: 2.12,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-031',
    code: 'PB4012UKS',
    name: 'Vibrating roller 448kg; single drum Benford 171BPP',
    category: 'compaction',
    description: 'Vibrating roller 448kg; single drum Benford 171BPP',
    rate: 1.96,
    unit: 'hr',
    costCode: 'NP01',
  },
  {
    id: 'plant-032',
    code: 'PE0301UKS',
    name: 'Rotovator - Petrol',
    category: 'general',
    description: 'Rotovator - Petrol',
    rate: 1.75,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-033',
    code: 'PF0104UKS',
    name: 'Poker Vibrator: Engine: 50 mm',
    category: 'general',
    description: 'Poker Vibrator: Engine: 50 mm',
    rate: 1.74,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-034',
    code: 'PB4008UKS',
    name: 'Steel Trench Sheets (m2)',
    category: 'general',
    description: 'Steel Trench Sheets (m2)',
    rate: 1.50,
    unit: 'day',
    costCode: 'NP02',
  },
  {
    id: 'plant-035',
    code: 'PC2012UKS',
    name: 'Melting & Pouring Set',
    category: 'general',
    description: 'Melting & Pouring Set',
    rate: 1.46,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-036',
    code: 'PB4018UKS',
    name: 'Paving Cutter',
    category: 'general',
    description: 'Paving Cutter',
    rate: 1.42,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-037',
    code: 'PC2013UKS',
    name: 'Beam Clamp Set',
    category: 'general',
    description: 'Beam Clamp Set',
    rate: 1.19,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-038',
    code: 'PE0302UKS',
    name: 'Mowing Machine - Petrol',
    category: 'general',
    description: 'Mowing Machine - Petrol',
    rate: 1.13,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-039',
    code: 'PB4006UKS',
    name: 'Kango Hammer',
    category: 'general',
    description: 'Kango Hammer',
    rate: 1.07,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-040',
    code: 'PB4011UKS',
    name: 'Stihl TS350 Disc Cutter',
    category: 'general',
    description: 'Stihl TS350 Disc Cutter',
    rate: 0.98,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-041',
    code: 'PJ3004UKS',
    name: 'Tyrolean Machine',
    category: 'general',
    description: 'Tyrolean Machine',
    rate: 0.64,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-042',
    code: 'PC2015UKS',
    name: 'Wall Clamp Set',
    category: 'general',
    description: 'Wall Clamp Set',
    rate: 0.33,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-043',
    code: 'PC2011UKS',
    name: 'Acrow Prop not exceeding 6.0m',
    category: 'general',
    description: 'Acrow Prop not exceeding 6.0m',
    rate: 0.21,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-044',
    code: 'PF0145UKS',
    name: 'Column Clamp: 500mm',
    category: 'general',
    description: 'Column Clamp: 500mm',
    rate: 0.21,
    unit: 'hr',
    costCode: 'NP02',
  },
  {
    id: 'plant-045',
    code: 'PC2010UKS',
    name: 'Acrow Prop not exceeding 3.0m',
    category: 'general',
    description: 'Acrow Prop not exceeding 3.0m',
    rate: 0.18,
    unit: 'hr',
    costCode: 'NP02',
  },
];

export const getPlantByName = (name: string): PlantRate | undefined => {
  return PLANT_RATES.find((p) => p.name.toLowerCase().includes(name.toLowerCase()));
};

export const getPlantByCode = (code: string): PlantRate | undefined => {
  return PLANT_RATES.find((p) => p.code === code);
};

export const getPlantByCategory = (category: string): PlantRate[] => {
  return PLANT_RATES.filter((p) => p.category === category);
};
